# Generated by Django 4.2.3 on 2023-07-12 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0005_rename_unit_ingredient_measurement_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="measurement_unit",
        ),
    ]
