# Generated by Django 4.2.3 on 2023-07-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("moderator", "moderator"),
                    ("user", "user"),
                ],
                default="admin",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
