run: # Запуск сервера разработки Django
	python3 manage.py runserver 

makemigrations: #Создание файлов миграции на основе изменений в моделях.
	python3 manage.py makemigrations 

migrate: # Применение миграций и обновление базы данных.
	python3 manage.py migrate 
	
